public struct RandomQuoteGenerator: QuoteGenerator {
    
    public init() { }
    
    private (set) var quotes: [Quote] = [
        Quote(owner: "Albert Einstein", message: "Life is like riding a bicycle. To keep your balance, you must keep moving."),
        Quote(owner: "Mahatma Gandhi", message: "Be the change that you wish to see in the world."),
        Quote(owner: "Oscar Wilde", message: "Be yourself; everyone else is already taken."),
        Quote(owner: "Marilyn Monroe", message: "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring."),
        Quote(owner: "Nelson Mandela", message: "The greatest glory in living lies not in never falling, but in rising every time we fall."),
        Quote(owner: "Walt Disney", message: "The way to get started is to quit talking and begin doing."),
        Quote(owner: "Eleanor Roosevelt", message: "The future belongs to those who believe in the beauty of their dreams."),
        Quote(owner: "Steve Jobs", message: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do."),
        Quote(owner: "Mother Teresa", message: "Spread love everywhere you go. Let no one ever come to you without leaving happier."),
        Quote(owner: "Confucius", message: "It does not matter how slowly you go as long as you do not stop."),
        Quote(owner: "Helen Keller", message: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart."),
        Quote(owner: "Abraham Lincoln", message: "In the end, it's not the years in your life that count. It's the life in your years."),
        Quote(owner: "Mark Twain", message: "The two most important days in your life are the day you are born and the day you find out why."),
        Quote(owner: "Martin Luther King Jr.", message: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that."),
        Quote(owner: "Maya Angelou", message: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel."),
        Quote(owner: "Vincent Van Gogh", message: "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced."),
        Quote(owner: "Rosa Parks", message: "I have learned over the years that when one's mind is made up, this diminishes fear."),
        Quote(owner: "John Lennon", message: "Life is what happens when you're busy making other plans."),
        Quote(owner: "J.K. Rowling", message: "It is our choices that show what we truly are, far more than our abilities."),
        Quote(owner: "Babe Ruth", message: "Every strike brings me closer to the next home run."),
        Quote(owner: "Winston Churchill", message: "Success is not final, failure is not fatal: It is the courage to continue that counts."),
        Quote(owner: "Helen Keller", message: "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us."),
        Quote(owner: "Franklin D. Roosevelt", message: "The only thing we have to fear is fear itself."),
        Quote(owner: "Audrey Hepburn", message: "Nothing is impossible, the word itself says 'I'm possible'!"),
        Quote(owner: "Albert Camus", message: "In the depth of winter, I finally learned that there was in me an invincible summer."),
        Quote(owner: "Neil Armstrong", message: "That's one small step for man, one giant leap for mankind."),
        Quote(owner: "Dalai Lama", message: "Happiness is not something ready made. It comes from your own actions."),
        Quote(owner: "Socrates", message: "The only true wisdom is in knowing you know nothing."),
        Quote(owner: "John F. Kennedy", message: "Ask not what your country can do for you, ask what you can do for your country."),
        Quote(owner: "Albert Schweitzer", message: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful."),
        Quote(owner: "Frida Kahlo", message: "Feet, what do I need you for when I have wings to fly?"),
        Quote(owner: "Charles Dickens", message: "It was the best of times, it was the worst of times."),
        Quote(owner: "Plato", message: "Music gives a soul to the universe, wings to the mind, flight to the imagination, and life to everything."),
        Quote(owner: "Marie Curie", message: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less."),
        Quote(owner: "Leo Tolstoy", message: "Everyone thinks of changing the world, but no one thinks of changing himself."),
        Quote(owner: "Harriet Tubman", message: "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world."),
        Quote(owner: "Thomas Edison", message: "I have not failed. I've just found 10,000 ways that won't work."),
        Quote(owner: "Ralph Waldo Emerson", message: "Do not go where the path may lead, go instead where there is no path and leave a trail."),
        Quote(owner: "Nikola Tesla", message: "The present is theirs; the future, for which I really worked, is mine."),
        Quote(owner: "Galileo Galilei", message: "You cannot teach a man anything; you can only help him find it within himself."),
        Quote(owner: "Emily Dickinson", message: "Hope is the thing with feathers that perches in the soul - and sings the tunes without the words - and never stops at all."),
        Quote(owner: "Walt Whitman", message: "Keep your face always toward the sunshine - and shadows will fall behind you."),
        Quote(owner: "Pablo Picasso", message: "Everything you can imagine is real."),
        Quote(owner: "Fyodor Dostoevsky", message: "Above all, don't lie to yourself. The man who lies to himself and listens to his own lie comes to a point that he cannot distinguish the truth within him, or around him, and so loses all respect for himself and for others. And having no respect he ceases to love."),
        Quote(owner: "Alexander Graham Bell", message: "When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us."),
        Quote(owner: "George Bernard Shaw", message: "Life isn't about finding yourself. Life is about creating yourself."),
        Quote(owner: "George Washington", message: "It is better to offer no excuse than a bad one."),
        Quote(owner: "Thomas Jefferson", message: "I'm a greater believer in luck, and I find the harder I work the more I have of it."),
        Quote(owner: "Henry Ford", message: "Whether you think you can, or you think you can't--you're right."),
        Quote(owner: "Anne Frank", message: "How wonderful it is that nobody need wait a single moment before starting to improve the world."),
        Quote(owner: "Ernest Hemingway", message: "The most painful thing is losing yourself in the process of loving someone too much, and forgetting that you are special too."),
        Quote(owner: "J.R.R. Tolkien", message: "Not all those who wander are lost."),
        Quote(owner: "George Eliot", message: "It is never too late to be what you might have been."),
        Quote(owner: "Margaret Mead", message: "Never doubt that a small group of thoughtful, committed citizens can change the world. Indeed, it is the only thing that ever has."),
        Quote(owner: "Aristotle", message: "It is during our darkest moments that we must focus to see the light."),
        Quote(owner: "Frederick Douglass", message: "If there is no struggle, there is no progress."),
        Quote(owner: "Heraclitus", message: "Change is the only constant in life."),
        Quote(owner: "Carl Sagan", message: "Somewhere, something incredible is waiting to be known."),
        Quote(owner: "Harvey Milk", message: "Hope will never be silent."),
        Quote(owner: "Sigmund Freud", message: "One day, in retrospect, the years of struggle will strike you as the most beautiful."),
        Quote(owner: "Jane Austen", message: "I declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book!"),
        Quote(owner: "Voltaire", message: "Judge a man by his questions rather than by his answers."),
        Quote(owner: "W. Clement Stone", message: "Whatever the mind of man can conceive and believe, it can achieve."),
        Quote(owner: "Bill Gates", message: "It's fine to celebrate success, but it is more important to heed the lessons of failure.")
    ]
    
    public func randomizeQuote() -> Quote {
        quotes.randomElement() ?? quotes[0]
    }
}
